[theme]
primaryColor = "#E4002B"                 # Rosa FIAP (bot√µes, sliders)
backgroundColor = "#0B0B0B"              # Fundo preto
secondaryBackgroundColor = "#1E1E1E"     # Cards / caixas
textColor = "#FFFFFF"                    # Texto branco
font = "sans serif"

